name: "Deploy site"

on:
  push:
    branches:
      - 'source'
  workflow_dispatch:
    # Allow manually running workflow
  
  schedule:
    - cron: '23 2 * * *'

env:
  OUTPUT: _html

jobs:
  build:
    name: Build python.be site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install Lektor
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
      - name: Build python.be site
        run: lektor build -O '${{ env.OUTPUT }}'
      - name: Deploy to Github Pages
        run: lektor deploy ghpages